Repository BCDA-APS/gemviz, pull requests merged in 2023-08, with the labels that each got.

#95 allow run(s) on last date to appear in timeline
  gemviz23/demo/date_time_range_slider.py
  gemviz23/demo/filterpanel.py
Labels: bug

#104 allow to match start time of last run
  gemviz23/demo/utils.py
Labels: bug

#112 identify the plottable data
  env.yml
  gemviz23/demo/analyze_run.py
  gemviz23/demo/filterpanel.py
  gemviz23/demo/resources/vizpanel.ui
  gemviz23/demo/resultwindow.py
  gemviz23/demo/utils.py
Labels: enhancement

#107 add refresh button (to re-apply filters)
  gemviz23/demo/date_time_range_slider.py
  gemviz23/demo/resources/back.bmp
  gemviz23/demo/resources/buttons.vsd
  gemviz23/demo/resources/date_time_range_slider.ui
  gemviz23/demo/resources/delete.bmp
  gemviz23/demo/resources/epicslogo101.bmp
  gemviz23/demo/resources/filterpanel.ui
  gemviz23/demo/resources/forward.bmp
  gemviz23/demo/resources/go.bmp
  gemviz23/demo/resources/home.bmp
  gemviz23/demo/resources/plus.bmp
  gemviz23/demo/resources/refresh.bmp
  gemviz23/demo/resources/set.bmp
  gemviz23/demo/resultwindow.py
Labels: task

#115 re-organize repository & rebrand as "gemviz"
  README.md
  archive/test/__init__.py
  archive/test/app.py
  archive/test/dummy_database.py
  archive/test/filter_function.py
  archive/test/hello.ui
  archive/test/result_function.py
  archive/test/resultswindow.py
  archive/test/resultswindow_tablemodel.py
  archive/test/resultwindow.ipynb
  archive/test/resultwindow.ui
  archive/test/test_fanny.py
  archive/test/test_fanny_2.ipynb
  archive/test/test_ollie.ipynb
  archive/test/test_ollie_2.ipynb
  archive/test/tiled_client_database_API.py
  archive/test/ui_files/.DS_Store
  archive/test/ui_files/Filter_Window.ui
  archive/test/ui_files/filter_gui_code.py
  archive/test/ui_files/filter_window_version2.ui
  archive/test/ui_files/mainwindow.ui
  archive/test/ui_files/result_window_table_widget.ui
  archive/test/ui_files/resultswindow.ui
  archive/test/ui_files/table_window.py
  archive/test/utils.py
  env.yml
  gemviz23/LICENSE
  gemviz23/__init__.py
  gemviz23/aboutdialog.py
  gemviz23/analyze_run.py
  gemviz23/app.py
  gemviz23/app_settings.py
  gemviz23/date_time_range_slider.py
  gemviz23/demo/LICENSE
  gemviz23/filterpanel.py
  gemviz23/mainwindow.py
  gemviz23/range_slider.py
  gemviz23/resources/aboutdialog.ui
  gemviz23/resources/back.bmp
  gemviz23/resources/buttons.vsd
  gemviz23/resources/date_time_range_slider.ui
  gemviz23/resources/delete.bmp
  gemviz23/resources/epicslogo101.bmp
  gemviz23/resources/filterpanel.ui
  gemviz23/resources/forward.bmp
  gemviz23/resources/go.bmp
  gemviz23/resources/home.bmp
  gemviz23/resources/mainwindow.ui
  gemviz23/resources/plus.bmp
  gemviz23/resources/refresh.bmp
  gemviz23/resources/resultwindow.ui
  gemviz23/resources/set.bmp
  gemviz23/resources/textwindow.ui
  gemviz23/resources/tiledserverdialog.ui
  gemviz23/resources/vizpanel.ui
  gemviz23/resultwindow.py
  gemviz23/textwindow.py
  gemviz23/tiledserverdialog.py
  gemviz23/utils.py
  gemviz23/vizpanel.py
Labels: enhancement, task

#116 use new artwork for push button icons
  .gitignore
  gemviz23/resources/apply.png
  gemviz23/resources/archive/back.bmp
  gemviz23/resources/archive/buttons.vsd
  gemviz23/resources/archive/delete.bmp
  gemviz23/resources/archive/epicslogo101.bmp
  gemviz23/resources/archive/forward.bmp
  gemviz23/resources/archive/go.bmp
  gemviz23/resources/archive/home.bmp
  gemviz23/resources/archive/plus.bmp
  gemviz23/resources/archive/refresh.bmp
  gemviz23/resources/archive/set.bmp
  gemviz23/resources/back.png
  gemviz23/resources/date_time_range_slider.ui
  gemviz23/resources/delete.png
  gemviz23/resources/first.png
  gemviz23/resources/icons.pptx
  gemviz23/resources/last.png
  gemviz23/resources/next.png
  gemviz23/resources/plus.png
  gemviz23/resources/refresh.png
  gemviz23/resources/resultwindow.ui
  gemviz23/resources/set.png
  gemviz23/resultwindow.py
Labels: task

#117 appy code style
  gemviz23/analyze_run.py
  gemviz23/app_settings.py
  gemviz23/date_time_range_slider.py
  gemviz23/filterpanel.py
  gemviz23/mainwindow.py
  gemviz23/resultwindow.py
  gemviz23/utils.py
  gemviz23/vizpanel.py
Labels: task

#120 rename gemviz23
  .gitignore
  gemviz/LICENSE
  gemviz/__init__.py
  gemviz/aboutdialog.py
  gemviz/analyze_run.py
  gemviz/app.py
  gemviz/app_settings.py
  gemviz/date_time_range_slider.py
  gemviz/filterpanel.py
  gemviz/mainwindow.py
  gemviz/range_slider.py
  gemviz/resources/aboutdialog.ui
  gemviz/resources/apply.png
  gemviz/resources/archive/back.bmp
  gemviz/resources/archive/buttons.vsd
  gemviz/resources/archive/delete.bmp
  gemviz/resources/archive/epicslogo101.bmp
  gemviz/resources/archive/forward.bmp
  gemviz/resources/archive/go.bmp
  gemviz/resources/archive/home.bmp
  gemviz/resources/archive/plus.bmp
  gemviz/resources/archive/refresh.bmp
  gemviz/resources/archive/set.bmp
  gemviz/resources/back.png
  gemviz/resources/date_time_range_slider.ui
  gemviz/resources/delete.png
  gemviz/resources/filterpanel.ui
  gemviz/resources/first.png
  gemviz/resources/icons.pptx
  gemviz/resources/last.png
  gemviz/resources/mainwindow.ui
  gemviz/resources/next.png
  gemviz/resources/plus.png
  gemviz/resources/refresh.png
  gemviz/resources/resultwindow.ui
  gemviz/resources/set.png
  gemviz/resources/textwindow.ui
  gemviz/resources/tiledserverdialog.ui
  gemviz/resources/vizpanel.ui
  gemviz/resultwindow.py
  gemviz/textwindow.py
  gemviz/tiledserverdialog.py
  gemviz/utils.py
  gemviz/vizpanel.py
Labels: task

#121 center column(s): Scan ID & #points
  gemviz/resultwindow.py
Labels: enhancement, task

#125 show last run on last page
  gemviz/resultwindow.py
Labels: bug

#126 refactor similar code to one method
  gemviz/resultwindow.py
Labels: question, task

#137 to be merged to #128 to fix PR comments
  gemviz/bluesky_runs_catalog.py
  gemviz/bluesky_runs_catalog_run_viz.py
  gemviz/bluesky_runs_catalog_search.py
  gemviz/bluesky_runs_catalog_table_view.py
  gemviz/date_time_range_slider.py
  gemviz/mainwindow.py
Labels: bug, enhancement

#128 Refactor as MVC
  README.md
  gemviz/aboutdialog.py
  gemviz/app.py
  gemviz/app_settings.py
  gemviz/bluesky_runs_catalog.py
  gemviz/bluesky_runs_catalog_run_viz.py
  gemviz/bluesky_runs_catalog_search.py
  gemviz/bluesky_runs_catalog_table_model.py
  gemviz/bluesky_runs_catalog_table_view.py
  gemviz/date_time_range_slider.py
  gemviz/mainwindow.py
  gemviz/resources/bluesky_runs_catalog.ui
  gemviz/resources/bluesky_runs_catalog_run_viz.ui
  gemviz/resources/bluesky_runs_catalog_search.ui
  gemviz/resources/bluesky_runs_catalog_table_view.ui
  gemviz/resources/mainwindow.ui
  gemviz/tiledserverdialog.py
  gemviz/utils.py
Labels: enhancement

#138 BUG #40 Fixes #40
  gemviz/mainwindow.py
Labels: bug

#139 ENH #136 delete the `archive/` directory
  archive/test/__init__.py
  archive/test/app.py
  archive/test/dummy_database.py
  archive/test/filter_function.py
  archive/test/hello.ui
  archive/test/result_function.py
  archive/test/resultswindow.py
  archive/test/resultswindow_tablemodel.py
  archive/test/resultwindow.ipynb
  archive/test/resultwindow.ui
  archive/test/test_fanny.py
  archive/test/test_fanny_2.ipynb
  archive/test/test_ollie.ipynb
  archive/test/test_ollie_2.ipynb
  archive/test/tiled_client_database_API.py
  archive/test/ui_files/.DS_Store
  archive/test/ui_files/Filter_Window.ui
  archive/test/ui_files/filter_gui_code.py
  archive/test/ui_files/filter_window_version2.ui
  archive/test/ui_files/mainwindow.ui
  archive/test/ui_files/result_window_table_widget.ui
  archive/test/ui_files/resultswindow.ui
  archive/test/ui_files/table_window.py
  archive/test/utils.py
Labels: task

#141 refactor of table columns with lambda
  gemviz/bluesky_runs_catalog_table_model.py
Labels: enhancement

#144 Use custom widgets
  gemviz/aboutdialog.py
  gemviz/bluesky_runs_catalog_search.py
  gemviz/date_time_range_slider.py
  gemviz/licensedialog.py
  gemviz/resources/bluesky_runs_catalog_search.ui
  gemviz/resources/date_time_range_slider.ui
  gemviz/resources/licensedialog.ui
  gemviz/resources/textwindow.ui
  gemviz/textwindow.py
Labels: enhancement

#145 add exception for text in scan_id
  gemviz/bluesky_runs_catalog_search.py
Labels: bug

#142 Fixes splitter_moved
  gemviz/bluesky_runs_catalog.py
Labels: bug

#147 Add tiled server QcomboBox
  gemviz/mainwindow.py
  gemviz/resources/mainwindow.ui
  gemviz/tiledserverdialog.py
Labels: enhancement

#152 make this package installable by pip
  .gitignore
  MANIFEST.in
  README.md
  env.yml
  gemviz/__init__.py
  gemviz/aboutdialog.py
  gemviz/analyze_run.py
  gemviz/app.py
  gemviz/app_settings.py
  gemviz/bluesky_runs_catalog.py
  gemviz/bluesky_runs_catalog_run_viz.py
  gemviz/bluesky_runs_catalog_search.py
  gemviz/bluesky_runs_catalog_table_model.py
  gemviz/bluesky_runs_catalog_table_view.py
  gemviz/date_time_range_slider.py
  gemviz/licensedialog.py
  gemviz/mainwindow.py
  gemviz/range_slider.py
  gemviz/resources/bluesky_runs_catalog_search.ui
  gemviz/resources/date_time_range_slider.ui
  gemviz/tiledserverdialog.py
  gemviz/utils.py
  pyproject.toml
Labels: enhancement, task
