Repository BCDA-APS/gemviz, pull requests merged in 2023-09, with the labels that each got.

#155 support command-line options: help & version
  gemviz/app.py
Labels: enhancement

#158 rename app_settings.py -> user_settings.py
  gemviz/bluesky_runs_catalog.py
  gemviz/mainwindow.py
  gemviz/tiledserverdialog.py
  gemviz/user_settings.py
Labels: task

#157 Mark unsuccessful runs with different background color in table
  gemviz/bluesky_runs_catalog_table_model.py
Labels: enhancement

#161 print() --> logger.debug (mostly)
  gemviz/aboutdialog.py
  gemviz/analyze_run.py
  gemviz/app.py
  gemviz/bluesky_runs_catalog.py
  gemviz/bluesky_runs_catalog_search.py
  gemviz/bluesky_runs_catalog_table_model.py
  gemviz/mainwindow.py
  gemviz/range_slider.py
  gemviz/user_settings.py
  gemviz/utils.py
Labels: task

#163 do not install tiled from conda-forge now
  env.yml
Labels: bug

#165 hoist icons from mdaviz
  gemviz/resources/back.png
  gemviz/resources/first.png
  gemviz/resources/last.png
  gemviz/resources/next.png
  gemviz/resources/open.png
  gemviz/resources/refresh.png
Labels: task

#164 raise custom exception and catch it if catalog too big to page
  gemviz/bluesky_runs_catalog_table_model.py
  gemviz/bluesky_runs_catalog_table_view.py
  gemviz/utils.py
Labels: bug

#167 remember last N servers in setting
  gemviz/mainwindow.py
  gemviz/tiledserverdialog.py
Labels: enhancement

#166 plot data
  env.yml
  gemviz/analyze_run.py
  gemviz/bluesky_runs_catalog.py
  gemviz/bluesky_runs_catalog_run_viz.py
  gemviz/bluesky_runs_catalog_search.py
  gemviz/bluesky_runs_catalog_table_model.py
  gemviz/bluesky_runs_catalog_table_view.py
  gemviz/chartview.py
  gemviz/mainwindow.py
  gemviz/resources/bluesky_runs_catalog.ui
  gemviz/resources/bluesky_runs_catalog_run_viz.ui
  gemviz/resources/bluesky_runs_catalog_table_view.ui
  gemviz/resources/select_fields_tableview.ui
  gemviz/resources/select_stream_fields.ui
  gemviz/select_fields_tablemodel.py
  gemviz/select_fields_tableview.py
  gemviz/select_stream_fields.py
  gemviz/tapi.py
  gemviz/utils.py
Labels: task

#175 start unit tests
  docs/source/_static/.gitkeep
  docs/source/index.rst
  docs/source/testing.rst
  gemviz/LICENSE
  gemviz/__init__.py
  gemviz/tests/__init__.py
  gemviz/tests/test_aboutdialog.py
  gemviz/tests/test_chartview.py
  gemviz/tests/test_init.py
  gemviz/tests/test_utils.py
  pyproject.toml
  requirements-dev.txt
Labels: task
