Repository BCDA-APS/gemviz, pull requests merged in 2023-07, with the labels that each got.

#27 display filter runs in table
  gemviz23/result_function.py
  gemviz23/ui_files/filter_window_version2.ui
  gemviz23/ui_files/result_window.ui
  gemviz23/ui_files/result_window_table_widget.ui
  gemviz23/ui_files/table_window.py
Labels: enhancement

#25 refactor mainwindow to storyboard
  gemviz23/demo/mainwindow.py
  gemviz23/demo/resources/filterpanel.ui
  gemviz23/demo/resources/mainwindow.ui
Labels: task

#28 Use .exec() instead of .show()
  gemviz23/demo/mainwindow.py
Labels: bug

#33 formatting adding results table ui
  gemviz23/demo/aboutdialog.py
  gemviz23/demo/app.py
  gemviz23/demo/filterpanel.py
  gemviz23/demo/mainwindow.py
  gemviz23/demo/resources/resultwindow.ui
  gemviz23/demo/resultwindow.py
  gemviz23/demo/textwindow.py
  gemviz23/demo/tiledserverdialog.py
  gemviz23/demo/utils.py
Labels: enhancement

#34 integrate filter UI into demo app #30
  gemviz23/demo/resources/filterpanel.ui
Labels: enhancement

#36 connect server, choose catalog, start filtering #35
  gemviz23/demo/filterpanel.py
  gemviz23/demo/mainwindow.py
  gemviz23/demo/resources/filterpanel.ui
  gemviz23/demo/utils.py
Labels: enhancement

#38 Date time slider
  gemviz23/demo/date_time_range_slider.py
  gemviz23/demo/filterpanel.py
  gemviz23/demo/range_slider.py
  gemviz23/demo/resources/date_time_range_slider.ui
  gemviz23/demo/resources/filterpanel.ui
  gemviz23/demo/resources/resultwindow.ui
  gemviz23/demo/tiledserverdialog.py
  gemviz23/demo/utils.py
Labels: enhancement

#41 Results window connected to tiled
  gemviz23/demo/mainwindow.py
  gemviz23/resultswindow.py
  gemviz23/resultswindow_tablemodel.py
  gemviz23/resultwindow.ui
Labels: enhancement

#55 work for refactor the filterpanel UI #49
  gemviz23/demo/mainwindow.py
  gemviz23/demo/resources/filterpanel.ui
  gemviz23/demo/resources/mainwindow.ui
Labels: enhancement

#56 Handles unexpected metadata results
  gemviz23/demo/resultwindow.py
Labels: bug

#62 select entire row
  gemviz23/demo/resources/resultwindow.ui
Labels: enhancement

#65 save QComboBox size selection of user
  gemviz23/demo/resultwindow.py
Labels: bug

#66 able to refresh catalog using return key in a filter textBox
  gemviz23/demo/filterpanel.py
  gemviz23/demo/resultwindow.py
Labels: enhancement

#67 use a filter catalog
  gemviz23/demo/filterpanel.py
  gemviz23/demo/resources/filterpanel.ui
  gemviz23/demo/resultwindow.py
Labels: enhancement

#73 increase maximum date for DateTimeRangeSlider widget
  gemviz23/demo/date_time_range_slider.py
Labels: task

#72 Generalize column labels & their access actions
  gemviz23/demo/resultwindow.py
Labels: enhancement

#76 Able to filter using detector names and separate using " , "
  gemviz23/demo/filterpanel.py
  gemviz23/demo/resources/filterpanel.ui
  gemviz23/demo/resultwindow.py
Labels: enhancement

#82 show some kind of data representation
  gemviz23/demo/resources/vizpanel.ui
  gemviz23/demo/resultwindow.py
  gemviz23/demo/utils.py
  gemviz23/demo/vizpanel.py
Labels: enhancement

#88 help create a conda environment
  env.yml
Labels: enhancement

#83 resolve problematic application crashes
  gemviz23/demo/filterpanel.py
  gemviz23/demo/resultwindow.py
Labels: bug

#85 len(catalog) sometimes reported as 1
  gemviz23/demo/resultwindow.py
Labels: bug

#90 do not crash app when chosen server cannot be opened
  gemviz23/demo/mainwindow.py
Labels: bug
