Repository BCDA-APS/gemviz, pull requests merged in 2024-02, with the labels that each got.

#194 made change so that if status is add, status becomes replace
  gemviz/bluesky_runs_catalog.py
Labels: bug

#210 update/extend copyright year to include 2024
  gemviz/LICENSE
  gemviz/__init__.py
  gemviz/aboutdialog.py
  gemviz/app.py
  gemviz/bluesky_runs_catalog.py
  gemviz/bluesky_runs_catalog_run_viz.py
  gemviz/bluesky_runs_catalog_search.py
  gemviz/bluesky_runs_catalog_table_model.py
  gemviz/bluesky_runs_catalog_table_view.py
  gemviz/chartview.py
  gemviz/date_time_range_slider.py
  gemviz/licensedialog.py
  gemviz/mainwindow.py
  gemviz/range_slider.py
  gemviz/select_fields_tablemodel.py
  gemviz/select_fields_tableview.py
  gemviz/select_stream_fields.py
  gemviz/tapi.py
  gemviz/tiledserverdialog.py
  gemviz/user_settings.py
  gemviz/utils.py
Labels: documentation, task

#211 pin python version to <3.12
  pyproject.toml
Labels: task

#206 refactor self.selections per Qt's pattern
  gemviz/select_fields_tablemodel.py
Labels: task
